# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master", "uralsky" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1
    
    # - uses: actions/checkout@v4
    # - name: Install uv
    #   uses: astral-sh/setup-uv@v5
    #   with:
    #       version: "0.6.14"

    # - name: "Set up Python"
    #   uses: actions/setup-python@v5
    #   with:
    #       python-version-file: ".python-version"
          
    # - name: Install the project
    #   run: | 
    #     uv sync --dev
    #     uv add pytest

    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Ruff
      run: ruff check --output-format=github .
      
    - name: Test with pytest
      run: |
        pytest tests.py
